### ISSUE TITLE
ASE's ATEK links & bounding boxes

### ISSUE THREAD

**Issue by hushell** [facebookresearch/efm3d#2]
Thank you for releasing your code & data! Excited to see yet another impactful work for 3D vision. 

I followed the [download instruction](https://github.com/facebookresearch/efm3d/blob/main/data/README.md), but didn't find `AriaSyntheticEnvironment_ATEK_download_urls.json`. In my case, the download page doesn't show the ATEK json file. 
<img width="945" alt="Screenshot 2024-10-03 at 17 02 14" src="https://github.com/user-attachments/assets/6c3bf1ae-dd35-4f23-a1f3-d8ceed5a8809">

Is the data release delayed? Totally understandable how difficult it is to go through the approvals. 

BTW, in the SceneScript paper, it says the ASE dataset has 100K scenes but from the download page the json file has only 10K scenes. Also, the additional 3M bboxes are not included as mentioned in EFM3D paper. Could you estimate the release date for these parts? 

Many thanks!

**Comment by hlzz** [comment]
Hi @hushell thanks for you interest and reporting this error. This is a bug on our side. Let's me follow up with that and get back to you shortly

**Comment by hlzz** [comment]
@hushell It should be fixed now. You should be able to follow that download instruction to get access to the data :)

**Comment by hushell** [comment]
@hlzz Thank you so much for the light-speed fix! I confirm the download links show up exactly the same as in your instruction.
