### ISSUE TITLE
Standard deviation aggregation

### ISSUE THREAD

**Issue by iammarvelous** [facebookresearch/efm3d#3]
The aggregation over time in the repo seems to be only mean aggregation, instead of both mean and std aggregation as stated in the paper. Did I miss anything there? Thanks.

https://github.com/facebookresearch/efm3d/blob/3e02fd8f4870260f2d0246e54edbd691170e32a6/efm3d/model/lifter.py#L379-L396

**Comment by hlzz** [comment]
Hi @iammarvelous the model we released is not exactly the same model config used to run the eval results in the paper. Your understanding is correct. The released code use mean aggregation instead of mean_std in the paper.
